### ISSUE TITLE
Add Heros and Vilain data

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#1]
Insert data through import.sql

- Heros data at https://github.com/quarkusio/quarkus-workshops/tree/master/quarkus-workshop-super-heroes/exercise-99-final/hero-api/src/main/resources

-  Vilains data at https://github.com/quarkusio/quarkus-workshops/tree/master/quarkus-workshop-super-heroes/exercise-99-final/vilain-api/src/main/resources

**Comment by cescoffier** [comment]
Fixed in master.
