### ISSUE TITLE
Quarkus 2.x - a.k.a the big rewrite

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-workshops#101]
This workshop was written initially on a very early version of Quarkus. It is still relevant but Quarkus has a lot more to offer and the workshop should demonstrate more such as continuous testing, dev services, resteasy reactive, hibernate reactive...

Also, there is really outdated content (packaging, smallrye-metrics...) that needs to be updated. Some recommendations are changing (Json-b -> Jackson, Resteasy -> Resteasy Reactive)

I've started working on a "big rewrite" with:

- [x] a villain service using Resteasy reactive + Hibernate ORM with Panache - demonstrate dev mode, dev services, and continuous testing
- [x] a hero service using Resteasy reactive + Hibernate reactive
- [ ] two variants of the fight service (imperative and reactive - like an API gateway)
- [x] improve the stats service with up to date Mutiny operators
- [x] reduce kafka configuration

@agoncal has also created #100 which is a very good idea!

**Comment by agoncal** [comment]
@cescoffier I'm giving the workshop in a few days. Because the POMs have been updated to Quarkus 2.x I'm updating the documentation. Let me update it first.... and then we'll do the "big rewrite" ;o)

Something to add is DevServices. Today the workshop uses Docker to start a Postgres for development. We should use DevService for development and keep the Postgres for prod

**Comment by cescoffier** [comment]
Yes, that's exactly what I have right now.

And no worries, I won't force push to the main branch during your workshop ( like a true super-villain 🦹🏿). I'm working from a branch.

**Comment by cescoffier** [comment]
To follow the progress - https://quarkus.io/quarkus-workshops/super-heroes/2.0/.

**Comment by fedinskiy** [comment]
@cescoffier what happened to the rest-hero directory[1]? Right now half of it is gone, is it going to be removed completely?

We use this project to validate that workshop examples work with RHBQ, so it would be nice to know, whether we need to rewrite our tests :-)

[1] https://github.com/quarkusio/quarkus-workshops/tree/main/quarkus-workshop-super-heroes/super-heroes/rest-hero

**Comment by cescoffier** [comment]
@fedinskiy There will be back (see #110). 

BTW, the previous code was compiling and passing the tests, but actually, was not working correctly.

**Comment by cescoffier** [comment]
GraalVM is covered a bit, but not much. The Native IT section was removed (because of a profile conflict).

**Comment by agoncal** [comment]
@cescoffier I wonder if we can close this issue (lots of rewrite has, and is being made).

WDYT ?
