### ISSUE TITLE
Exclude rest-fights/** twice

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#107]
@cescoffier you've exclude rest-fights twice:

https://github.com/quarkusio/quarkus-workshops/blob/eda46b9bc77efc806260a81725a4cef9436a11a5/quarkus-workshop-super-heroes/assembly.xml#L28
https://github.com/quarkusio/quarkus-workshops/blob/eda46b9bc77efc806260a81725a4cef9436a11a5/quarkus-workshop-super-heroes/assembly.xml#L30

Is this just a duplicate, and didn't you want to exclude rest-villains instead ?

**Comment by cescoffier** [comment]
Probably a copy-paste-edit pattern where I failed the "edit" part. It should exclude rest-heroes, rest-villains, rest-fights, and event-statistics.
