### ISSUE TITLE
Confusing note about Quarkus Universe

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#108]
In the documentation at https://github.com/quarkusio/quarkus-workshops/blob/main/quarkus-workshop-super-heroes/docs/src/main/asciidoc/1-rest/rest-bootstrapping.adoc#directory-structure there is this not about Quarkus Universe:

```
The Quarkus Universe includes Quarkus as well as third-party extensions, like Apache Camel or Kogito.
```

But nowhere else Quarkus Universe is mentioned. @cescoffier  is it an old note that we should get rid of ?

**Comment by cescoffier** [comment]
Yes, it's an old note. We should remove it.

**Comment by agoncal** [comment]
@cescoffier ok, I'm removing it.

BTW Clement, I am on Zulip and would like to have a little chat with you when you are available ;o)
