### ISSUE TITLE
levelMultiplier not yet implemented

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#109]
@cescoffier At the VillainService step, the documentation mentions a `levelMultiplier` https://github.com/quarkusio/quarkus-workshops/blob/main/quarkus-workshop-super-heroes/docs/src/main/asciidoc/1-rest/rest-orm.adoc#villain-service

```
    public Villain persistVillain(@Valid Villain villain) {
        villain.level = villain.level * levelMultiplier;
        villain.persist();
        return villain;
    }
```

At that stage, the code does not compile because `levelMultiplier` (you mention it later). At this stage, do you want to skip it from the code, or just declare the variable with a default value (and then configure it) ?

**Comment by cescoffier** [comment]
I would remove it from the code. That was a mistake when I copy/paste the code (I guess)

**Comment by agoncal** [comment]
Done! I've removed it. But be careful when you start including parts of code with Asciidoc ;o)
