### ISSUE TITLE
Package the UI as a standalone blob

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-workshops#12]

**Comment by cescoffier** [comment]
Fixed in master

**Comment by cescoffier** [comment]
UI is now served from: http://localhost:8082/super-heroes/

**Comment by agoncal** [comment]
@cescoffier how did you bundle it ? Wondering if we could use https://github.com/eirslett/frontend-maven-plugin to automate it with Maven

**Comment by cescoffier** [comment]
Yes we can use the frontend-maven-plugin.

What would be ideal is to use this plugin to generate the "prod" files, zip them with the maven assembly plugin and having the fight microservice depends on this artifact. However, this approach is going to introduce a long build time for the attendees. So right now, I've just made a `package.sh` (Bash forever!)

**Comment by agoncal** [comment]
@cescoffier right, let's keep in simple then
