### ISSUE TITLE
Extension section is missing VersionConfig

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus-workshops#126]
The diagram in the "Writing a Quarkus extension" section mentions VersionConfig with `enabled` parameter. This is also mentioned here and there in the section but the config is totally omitted. Is this intentional or can I fix the section to add config example as depicted in the diagram?

**Comment by xstefank** [comment]
@cescoffier maybe you know?

**Comment by cescoffier** [comment]
I think the section must be edited and add that parameter.
