### ISSUE TITLE
Synchronize Super Heroes workshop and Super Heroes sample

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#136]
@aureamunoz @cescoffier lately I've been working on the [Super Heroes](https://github.com/quarkusio/quarkus-super-heroes) sample app that @edeandrea has created. It is based on our original Super Hero, but Eric has introduced a few enhancements that, I think, could be ported back.

# Differences

Eric, correct me if I'm wrong, but here is a list of differences I've noticed:

**Global**:
* GitHub actions to automatically create Docker files for each microservice for Docker Compose and K8s
* Apicurio is used by Fights and Statistics to validate the messages against an Avro Fight schema
* Each Java project uses sub packages (eg. domain, endpoint, service) instead of being flat at the root package
* Classes tend to have more Java doc that the original code
* Use Jacoco
* Use Micrometer
* Code formatting is different
* `toString`, `equals`, `hashCode` methods have been introduced

**Statistics Microservice**:
* `Score` and `TeamScore` beans do not use public attributes but instead private attributes with getters/setters
* `EventStatsWebSocket` superclass is inherited by `TopWinnerWebSocket` and `TeamStatsWebSocket` 
* Logger is statically created (`Logger.getLogger(SuperStats.class)`) instead of being injected.
* Integration tests have been created (using Kafka companion)

**Villain Microservice**:
* Uses MapStruct (has a few Mapper files)
* Uses the `var` keyword (`var response = this.villainResource.hello();`)
* Some `VillainService` return `Optional`
* Rest endpoints have `PATCH` methods

**Hero Microservice**:
* Uses MapStruct (has a few Mapper files)
* Use constructor injection instead of `@Inject`
* Uses a Panache repository (`HeroRepository`)
* Application YAML instead of properties

**Fights Microservice**:
* Stored Fights in MongoDB
* `Hero` and `Villains` beans do not use public attributes but instead private attributes with getters/setters
* Fight pings Villain and Hero microservices

# To Synch or not to Synch

We have to keep in mind that the workshop is for beginners and still need to target this audience. So we cannot synch all the modifications in order to keep it simple (eg. we can leave Kubernetes or Apicurio). But I still think that we could synch some changes.

**Good to be synched**:

* _Classes tend to have more Java doc that the original code_: We could synch the Java doc (see #143)
* _Use the `var` keyword_: I think it's time to add a few `var` keywords
* _Services returning Optional_: It would be good to return optional in our services
* _Use constructor injection instead of `@Inject`_: Good because developers will then use several ways of injecting. Showing both methods make sense
* _Uses a Panache repository_: Good because developers would learn more about Panache
* _Application YAML instead of properties_: Good for Spring developers who might have been used to YAML and don't know it's supported in Quarkus. Showing both methods make sense
* _Stored Fights in MongoDB_: I quite the idea of introducing MongoDB. And with Panache, it's not a lot of work

**Not sure about being synched**:

* _Each Java project uses sub packages_: Having all the code flatten at the root directory is easier that dispatching it to subpackages (eg. domain, endpoint, service). In real life we tend to do it, but for simplicity I will keep it as it is (even if it's a pain when doing diffs between both repos)
* _Rest endpoints use PATCH methods_: Not sure about this one, we already have PUT and POST, that means we would have to carefully explain when to use one or the other
* _Code formatting_: I would like both projects to have the same code formatting (easier when doing diffs) but it's one of this topic that we could all lose a lot of time
* _Beans do not use public attributes but instead private attributes with getters/setters_: Some developers might think that only public attributes can be used with Quarkus instead of good old private ones with get/sets.
* _`toString`, `equals`, `hashCode` methods have been introduced_: I like that our beans are sweet and simple with not much code.... but these methods are often used in real life

I think all the other changes will bring more complexity and will not help attendees finishing the workshop (eg. Apicurio, Mapstruct, PATCH, K8s etc).

@aureamunoz @cescoffier @edeandrea what do you think?

**Comment by edeandrea** [comment]
I can't comment in depth right now (I'm on PTO), but in heroes and villains services the get by id methods in the rest later also return 404 if nothing is found (rather than 200 with empty payload). The fights service handles this within the fault tolerance as well.

**Comment by aureamunoz** [comment]
Hi!

I totally agree with the `Good to be synched` list and I would also add these :point_down: from the other list. 

- Beans do not use public attributes but instead private attributes with getters/setters: Some developers might think that only public attributes can be used with Quarkus instead of good old private ones with get/sets.

- toString, equals, hashCode methods have been introduced: I like that our beans are sweet and simple with not much code.... but these methods are often used in real life

**Comment by edeandrea** [comment]
> * Beans do not use public attributes but instead private attributes with getters/setters: Some developers might think that only public attributes can be used with Quarkus instead of good old private ones with get/sets.

I agree and hate public attributes. That being said, some of the services use that pattern (active record pattern) and others use private fields with getters/setters (repository pattern). The sample app was done that way on purpose specifically to show this point - that its possible to do it both ways.

> * toString, equals, hashCode methods have been introduced: I like that our beans are sweet and simple with not much code.... but these methods are often used in real life

You are right - in real life, generally, these are needed, especially if you are caching beans. `toString` is important IMO, especially when trying to debug and/or log things. Just seeing `Object@XIOIOPE()*jkljklsdf8` isn't helpful in a debugger :)

**Comment by rafaeltuelho** [comment]
What's the best way to start working on this sync? Should we start creating PRs for each point listed above or send one PR covering a chunk of the points that need to be synced?

**Comment by rafaeltuelho** [comment]
> > * toString, equals, hashCode methods have been introduced: I like that our beans are sweet and simple with not much code.... but these methods are often used in real life
> 
> You are right - in real life, generally, these are needed, especially if you are caching beans. `toString` is important IMO, especially when trying to debug and/or log things. Just seeing `Object@XIOIOPE()*jkljklsdf8` isn't helpful in a debugger :)

What about introducing **Lombok** for this type of boilerplate code?

**Comment by edeandrea** [comment]
> What about introducing Lombok for this type of boilerplate code?

Lombok and I have a hate/hate relationship. I don't believe we'll be bringing it into the sample app. It was there actually and we took it out.

**Comment by cescoffier** [comment]
Please avoid lombok, it makes importing the project a lot more complex (you need to enable annotation processing, and must run compilation first...)

**Comment by holly-cummins** [comment]
I've also spotted some differences in testing; for example, the workshop uses `@Mock` for the proxies, and the main repo has a different test mechanism.

**Comment by agoncal** [comment]
Closing this issue as both Hero Workshop and Hero Sample are less and less compatible. Let's keep them separate
