### ISSUE TITLE
Could not find artifact extension-version-deployment

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#141]
@cescoffier When I build the project with the `complete` profile, I get the following error:

```
quarkus-workshop-super-heroes$  mvn clean install -Pcomplete

[INFO] Quarkus Workshop :: Super-Heroes :: Super Heroes UI 01 SUCCESS [  3.196 s]
[INFO] Quarkus Workshop :: Super-Heroes :: Load Super Heroes 01 SUCCESS [  0.809 s]
[INFO] Extension Version - Parent 1.0.0-SNAPSHOT .......... SUCCESS [  0.007 s]
[INFO] Extension Version - Runtime 1.0.0-SNAPSHOT ......... SUCCESS [  0.934 s]
[INFO] Quarkus Workshop :: Super-Heroes :: Villains Microservice 1.0.0-SNAPSHOT FAILURE [  2.023 s]
[INFO] Quarkus Workshop :: Super-Heroes :: Heroes Microservice 1.0.0-SNAPSHOT SKIPPED
[INFO] Quarkus Workshop :: Super-Heroes :: Fights Microservice 1.0.0-SNAPSHOT SKIPPED
[INFO] Quarkus Workshop :: Super-Heroes :: Statistics Microservice 1.0.0-SNAPSHOT SKIPPED
[INFO] Extension Version - Deployment 1.0.0-SNAPSHOT ...... SKIPPED
[INFO] Quarkus Workshop :: Super-Heroes :: R00T 2.0 ....... SKIPPED

Failed to create the application model for io.quarkus.workshop.super-heroes:rest-villains::jar:1.0.0-SNAPSHOT: Failed to resolve artifacts: Could not find artifact io.quarkus.workshop.super-heroes:extension-version-deployment:jar:1.0.0-SNAPSHOT
```

I've never written an extension, so I don't know how it works. The extension runtime is built first, and then Villain (which depends on it). But looks like Villain also needs the deployment because it generates a `target/classes/META-INF/quarkus-extension.properties` file with:

```
deployment-artifact=io.quarkus.workshop.super-heroes\:extension-version-deployment\:1.0.0-SNAPSHOT
```

Anything missing in the extension ?

**Comment by cescoffier** [comment]
nothing missing in the extension, however, extensions cannot be part of the same maven reactor without a lot of exclusion to constrain the ordering. There are the commands you need to run in https://github.com/quarkusio/quarkus-workshops/blob/main/quarkus-workshop-super-heroes/docs/src/docs/asciidoc/0-introduction/introduction-preparing.adoc#the-completed-workshop.

**Comment by agoncal** [comment]
Ok, so we need to change the README. I was first following the README (not the workshop itself), so it's kind of confusing. I'll change it. Thanks

https://github.com/quarkusio/quarkus-workshops/tree/main/quarkus-workshop-super-heroes#build
