### ISSUE TITLE
Cannot build the complete workshop

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#145]
When you read the workshop on how [to build it](https://quarkus.io/quarkus-workshops/super-heroes/#_the_completed_workshop), it's mentioned that you need to execute the following commands:

```
cd super-heroes
> mvn clean install -f extension-version
> mvn clean install -Pcomplete
```

This does not work as there is no `pom.xml` at the root of the `super-heroes` directory. So `mvn clean install -Pcomplete` does not work.

Either we use to have a `pom.xml` at the root, or something has changed.

See  #141

**Comment by cescoffier** [comment]
I think it should be executed from the `quarkus-workshop-super-heroes` directory and so it should be:

```
> mvn clean install -f super-heroes/extension-version
> mvn clean install -Pcomplete
```

**Comment by agoncal** [comment]
Ok, let's do that. It's easier than introducing another `pom.xml`
