### ISSUE TITLE
Imperative and/or reactive villains

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#146]
In our guide [when bootstrapping the Villains microservice](https://quarkus.io/quarkus-workshops/super-heroes/#rest), I find it confusing that we mention "classic" microservice, "imperative", but then use the reactive extensions. Wouldn't it be clearer not to use any reactive extension on Villains ?

```
-Dextensions="resteasy-reactive-jackson"
```

**Comment by cescoffier** [comment]
We want to be sure that all the services use resteasy reactive (even if they do not use reactive programming).

**Comment by agoncal** [comment]
Ok, but we need to explain why. On the first lines we write "imperative", and then "reactive". We should at least say that we do not use anything reactive in the code, but yes, we do use a reactive extension because xxxxx (and to be honest, at this very beginning of the workshop, I leave you write something easy and simple so the reader does not already get lost ;o)
