### ISSUE TITLE
Add logs to each method in the REST resources

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#154]
When deployed in the cloud, if something goes wrong, having logs is handy. We should add entry logs to all the resources methods (in INFO level) so we can watch logs passing by.

**Comment by carljmosca** [comment]
looks like the fight resource has some (debug) logging - happy to add/change anything in particular thoughts on this>

**Comment by agoncal** [comment]
Closing as there are already logs in each REST resource
