### ISSUE TITLE
Document the publishing process

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#175]
@cescoffier could you document how the documentation is publishing? @roryp is trying to fix a broken link in the doc, but we don't know how publication is done

**Comment by cescoffier** [comment]
It's automatically published on merge:
See https://github.com/quarkusio/quarkus-workshops/blob/main/.github/workflows/build.yml#L34-L56.

**Comment by agoncal** [comment]
Thanks.

@roryp have a look and let us know if you need more help

**Comment by holly-cummins** [comment]
This can probably be closed now, I think.
