### ISSUE TITLE
Github page is down https://quarkus.io/quarkus-workshops/super-heroes/index.html

### ISSUE THREAD

**Issue by roryp** [quarkusio/quarkus-workshops#186]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/6388864/194301864-60e90de0-a86e-497d-a919-48adec55df73.png">

@cescoffier 
cc @agoncal

**Comment by cescoffier** [comment]
Probably due to #184

**Comment by cescoffier** [comment]
Ok, it's a copy issue, the web page is on http://quarkus.io/quarkus-workshops/. 

On it.

**Comment by roryp** [comment]
the Azure version is still now working :
https://quarkus.io/quarkus-workshops/super-heroes/index-azure.html

[image: image.png]

**Comment by cescoffier** [comment]
Well... that was an attempt to fix the issue (the commit says "should fix ..." not "fix ..."

**Comment by cescoffier** [comment]
@roryp can you check if things are back to normal from your side?

**Comment by cescoffier** [comment]
If everything is back to normal, you can close the issue.
