### ISSUE TITLE
Creating an invalid item should fail

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#2]
At the moment, creating an invalid Hero or Villain works and it shouldn't. To test this behavior we have the `HeroResourceTest` class with a few test cases. The method [shouldNotAddInvalidItem](https://github.com/quarkusio/quarkus-workshops/blob/master/quarkus-workshop-super-heroes/exercise-99-final/hero-api/src/test/java/io/quarkus/workshop/superheroes/hero/HeroResourceTest.java#L109) creates an invalid hero with a null name and a level of zero, does an HTTP POST and excepts a 400 (but it gets a 201):

```
    @Test
    void shouldNotAddInvalidItem() {
        Hero hero = new Hero();
        hero.name = null;
        hero.otherName = DEFAULT_OTHER_NAME;
        hero.picture = DEFAULT_PICTURE;
        hero.powers = DEFAULT_POWERS;
        hero.level = 0;

        given()
            .body(hero)
            .header(CONTENT_TYPE, APPLICATION_JSON)
            .header(ACCEPT, APPLICATION_JSON)
            .when()
            .post("/api/heroes")
            .then()
            .statusCode(BAD_REQUEST.getStatusCode());
    }
```

If you look at the [Hero](https://github.com/quarkusio/quarkus-workshops/blob/master/quarkus-workshop-super-heroes/exercise-99-final/hero-api/src/main/java/io/quarkus/workshop/superheroes/hero/Hero.java#L17) entity it has a `@NotNull` on name and `@Min(1)` on level:

```
@Entity
public class Hero extends PanacheEntity {

    @NotNull
    @Size(min = 3, max = 50)
    public String name;
    public String otherName;
    @NotNull
    @Min(1)
    public int level;
```

The `HeroResource` REST Endpoint has a [create](https://github.com/quarkusio/quarkus-workshops/blob/master/quarkus-workshop-super-heroes/exercise-99-final/hero-api/src/main/java/io/quarkus/workshop/superheroes/hero/HeroResource.java#L72) method that validates and invalid Hero (same for the [service](https://github.com/quarkusio/quarkus-workshops/blob/master/quarkus-workshop-super-heroes/exercise-99-final/hero-api/src/main/java/io/quarkus/workshop/superheroes/hero/HeroService.java#L34)):

```
    @POST
    public Response create(@Valid Hero hero, @Context UriInfo uriInfo) {
        hero = service.createHero(hero);
        UriBuilder builder = uriInfo.getAbsolutePathBuilder().path(Long.toString(hero.id));
        LOGGER.debug("New hero created with URI " + builder.build().toString());
        return Response.created(builder.build()).build();
    }
```

At the moment the `shouldNotAddInvalidItem` succeeds but it should fail.

Same for Villain

**Comment by cescoffier** [comment]
Just missing `quarkus-hibernate-validator` dependency. 

Fixing.
