### ISSUE TITLE
Setting quarkus.http.cors=true does not work

### ISSUE THREAD

**Issue by omasseau** [quarkusio/quarkus-workshops#223]
Following https://quarkus.io/quarkus-workshops/super-heroes/#microservices-cors, 
I added quarkus.http.cors=true in application.properties of rest-fights but I still get a CORS error when the front is calling the rest service: 

![image](https://user-images.githubusercontent.com/11772429/232334057-670810f9-eb35-4649-8545-ec6e3f1f99a6.png)

As you can see quarkus.http.cors is correctly set : 
![image](https://user-images.githubusercontent.com/11772429/232334137-16af9886-45fc-4571-9cbc-16cd823f4bb4.png)

Is quarkus.http.cors=true really enough ?

**Comment by cescoffier** [comment]
It is not enough anymore. You need to set the origin to the list of valid origin or *

**Comment by omasseau** [comment]
> It is not enough anymore. You need to set the origin to the list of valid origin or *

Thanks, adding 
`quarkus.http.cors.origins=*`
in application.properties indeed fixes the problem.
