### ISSUE TITLE
Add the power to the Angular UI

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#23]
Heroes and Villains should have the power displayed on the UI. ATM there is only the name and level:

<img width="1174" alt="Capture d’écran 2019-10-11 à 11 56 51" src="https://user-images.githubusercontent.com/729277/66643103-5cb43a00-ec1e-11e9-9f5a-c2e8f5fecf17.png">

**Comment by cescoffier** [comment]
Fixed in master
