### ISSUE TITLE
Discuss how to address import ambiguity

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus-workshops#25]
In the REST module some imports are not obvious:

* HeroService
    * REQUIRED
* HeroResource
    * Logger
    * Response
    * PathParam
* HeroResourceTest
    * Random
    * CONTENT_TYPE
    * ACCEPT
    * HttpHeaders
    * assertEquals (method)
    * assertTrue (method)
    * assertNotNull (method)
    * get (method)
    * TypeRef
    
* HeroService (config):
    * ConfigProperty

* HeroREsource (OpenAPI):
    * Parameter
    * SchemaType

* HeroApplication:
    * Application (jax-rs one I think)

**Comment by cescoffier** [comment]
Done, I'm now:

* either including the imports in the code snippet
* or indicate the import to add explicitly
