### ISSUE TITLE
Reference to the docker compose infrastructure directory does not work

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus-workshops#27]
The guide (rest-transaction-orm) has this

> Go to https://raw.githubusercontent.com/quarkusio/quarkus-workshops/master/quarkus-workshop-super-heroes/super-heroes/infrastructure and download the entire code into the infrastructure directory. 

This link does not work, you cannot point to a directory in GitHub raw mode. we need an alternative.

**Comment by agoncal** [comment]
Oh. We actually do that for the UI and the Loader too. Let's use the `github.url` variable instead. I'm on this issue.

**Comment by cescoffier** [comment]
It's going to be tricky to ask them to download hundreds of files individually.

**Comment by agoncal** [comment]
Oh, and what about a Maven Assembly so we package these directories (intractructure, ui-super-heroes and load-super-heroes) into a zip file, and just ask the attendees to download the zip and unzip it into the folder ?

**Comment by agoncal** [comment]
Ok. I'll package the 3 projects into zip files then

**Comment by agoncal** [comment]
See https://github.com/quarkusio/quarkus-workshops/commit/2bd564fe7d17abd21535835f6b2b42c36fcb4b27
