### ISSUE TITLE
Wrong entity IDs in examples

### ISSUE THREAD

**Issue by mocenas** [quarkusio/quarkus-workshops#270]
In section https://quarkus.io/quarkus-workshops/super-heroes/linux/spine.html#_running_and_testing_the_application we should insert new villain and then get it, using curl, querying for villain ID 582. 
Referenced [import.sql](https://raw.githubusercontent.com/quarkusio/quarkus-workshops/refs/heads/main/quarkus-workshop-super-heroes/super-heroes/rest-villains/src/main/resources/import.sql) inserts only 570 villains (IDs 0-569), so newly injected villain has ID 570, not 582.

Similarly for heroes in https://quarkus.io/quarkus-workshops/super-heroes/linux/spine.html#_running_testing_and_packaging_the_application we should query for new hero with ID 952. but [import.sql](https://raw.githubusercontent.com/quarkusio/quarkus-workshops/refs/heads/main/quarkus-workshop-super-heroes/super-heroes/rest-heroes/src/main/resources/import.sql) injects only 941 villains (IDs 0-940). New hero has ID 941 not 952.

**Comment by agoncal** [comment]
This is just an example. Sequences implementation can change. Here the sequence increments by 50

```
ALTER SEQUENCE villain_seq RESTART WITH 50;
```

I am leaving this example but adding some note to explain that the number could be different
