### ISSUE TITLE
Bundle a node-v16.16.0-darwin-x64.tar.gz in the ZIP file

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#275]
Today accessing https://nodejs.org/dist/v16.16.0/ and downloading `node-v16.16.0-darwin-x64.tar.gz` took 45 minutes. So running/testing with UI would always fail. I had to download `node-v16.16.0-darwin-x64.tar.gz` myself and copy it into `ui-super-heroes/.quinoa/cache`.

We should bundle a version of `node-v16.16.0-darwin-x64.tar.gz`  in the ZIP file in case the attendees have the same problem.

**Comment by holly-cummins** [comment]
Actually, thinking about this more, we'd probably need to bundle the node image for every OS in the zip file. That would increase the weight a lot. It would help the case where people do the pre-work before they get to the conference, but if people wait until they're on the conference site, it would actually make the slowness of downloads worse. What do you think, @agoncal?

We tune the instructions for people's OS, so we could make a per-os zip and link to it from the instructions, but it starts to get complex. I guess we'd want an all-OS zip for the default instructions, and then tailored zips for macos, etc - but we'd need to include both intel and apple silicon images, even for the "macos" version.

**Comment by agoncal** [comment]
We will create a new diretory on GitHub and push all the ZIP files for all the platforms

**Comment by holly-cummins** [comment]
We have decided it will be too inefficient to bundle 4 node versions into each zip download; but we need a plan B if people are affected by the same slow downloads as Antonio. We could have a USB key, but that's cumbersome, so instead, we can use the same mechanism as we use to download the zip file.

**Comment by holly-cummins** [comment]
Thinking about it a third time, maybe we should make a version of the zip for each platform with the node version for that platform in it, and when people are running a platform-specific workshop, link to that zip.

**Comment by holly-cummins** [comment]
Another option would be to switch to web bundler - https://docs.quarkiverse.io/quarkus-web-bundler/dev/index.html - that would bypass node entirely, but we'd have to rewrite the dependencies into mvnpm format.

**Comment by agoncal** [comment]
@holly-cummins do you think we could make it before Devoxx BE ?

**Comment by holly-cummins** [comment]
It turns out the problem was with the download library. Quinoa have now updated to use a vertx library, and the download is fast.

**Comment by geoand** [comment]
Vertx everywhere!!!

**Comment by agoncal** [comment]
Really good news !!!
