### ISSUE TITLE
InjectMock being deprecated from Quarkus 3.2

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#277]
In `FightResourceTest` we have the following code:

```java
    @InjectMock(convertScopes = true)
    @RestClient
    HeroProxy heroProxy;
```

The `io.quarkus.test.junit.mockito.InjectMock` API is deprecated from Quarkus 3.2:

> Deprecated
> Use io.quarkus.test.InjectMock and MockitoConfig instead.

**Comment by agoncal** [comment]
@geoand Damn. I introduced a new one in the Narration microservice. Do you want to have a look ? https://github.com/quarkusio/quarkus-workshops/blob/main/quarkus-workshop-super-heroes/super-heroes/rest-narration/src/test/java/io/quarkus/workshop/superheroes/narration/NarrationResourceTest.java#L28

**Comment by geoand** [comment]
Sure yeah, I'll rebase my PR

**Comment by geoand** [comment]
PR updated
