### ISSUE TITLE
Hero test fail after adding OpenAPI

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus-workshops#28]
Since in the preceding section we added a lwvel multiplier on persist, the test suite fails as it expect power level of 42 and 42*3 is returned.

Should we ask user to set back level to 1 at the end of the config section?

**Comment by agoncal** [comment]
@emmanuelbernard I have to give it a try, but what is the relation between the power level multiplier and the OpenAPI making the test fail ? @cescoffier mentioned there were problems with OpenAPI but I thought they were solved in the 0.24

**Comment by cescoffier** [comment]
Hum, normally I fixed them and the issues were in hot-reload only

**Comment by emmanuelbernard** [comment]
To be clear it has nothing to do with OpenAPI. It’s just the time in the
guide where we are asked to run tests again. In practice anyone running the
tests after the config part have it fail.

**Comment by cescoffier** [comment]
Fixed.
