### ISSUE TITLE
Link to workshop-specific Zulip from workshop pages

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus-workshops#285]
It would be nice to have a quarkus-workshops group and a stream in the group for each workshop instance we run. Since zulip has a web client and the workshop instructions are web-based, we should be able to do a nice integration. This might bring out more shy questions.

We could also link to the main Quarkus zulip. 

As suggested by @agoncal, cc @maxandersen @geoand

**Comment by agoncal** [comment]
Looks like it's this URL. Can you all confirm: https://quarkusio.zulipchat.com/#narrow/stream/402952-workshops

**Comment by cescoffier** [comment]
Some time ago, I dreamed of integrating the users Zulip chat in the dev UI directly. So the new developers could interact with us directly..... Then I woke up and never had time to do anything.

Maybe @phillip-kruger is up for the challenge. When it's about front-end, he realized my dreams 🥇

**Comment by phillip-kruger** [comment]
Let me know where I can help.
