### ISSUE TITLE
Use config form instead of mp-rest/url

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#292]
In https://github.com/quarkusio/quarkus-workshops/pull/287/files/85ca6e481241b0a19e2bce4c062d910fdb181da9#r1314849246 @geoand mentioned:

> Not part of this PR, but we should probably use the config form that makes this a lot simpler. I can do that in a follow up for all the REST Clients involved

This is about updating the `rest-fights/src/main/resources/application.properties` properties:

```properties
io.quarkus.workshop.superheroes.fight.client.NarrationProxy/mp-rest/url=http://localhost:8086
```

**Comment by geoand** [comment]
See https://github.com/quarkusio/quarkus-workshops/pull/293
