### ISSUE TITLE
Have a Core and Optional sections in the workshop

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#296]
The core of the workshop should be:

* UI
* Fight
* Villain
* Heroes

And then we should have optional sections (using guards)

* Statistics with Kafka
* Contract testing with Pact
* IA with semantic kernel
* GraalVM
* Minikube
* Azure

**Comment by holly-cummins** [comment]
Also related to https://github.com/quarkusio/quarkus-workshops/issues/57

**Comment by agoncal** [comment]
@holly-cummins @geoand @cescoffier @maxandersen by introducing a "core" section for the workshop, and then a bunch of optional sections, our page organisation is not great. Today we have:

* 0-introduction
* 1-rest
* 2-quarkus
* 3-reactive
* 5a-contract-testing
* 5b-ai
* 9-kubernetes
* 10-conclusion

What about instead having:

* core-introduction
* core-rest
* core-quarkus
* core-reactive
* core-conclusion
* optional-contract-testing
* optional-ai
* optional-kubernetes

**Comment by geoand** [comment]
Yeah, I think that makes a lot of sense

**Comment by holly-cummins** [comment]
Yes, the numbers are quite fragile, happy to replace them.
