### ISSUE TITLE
Improve profile section to show some usages

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus-workshops#30]
We can improve the profile section easily by adding some profile settings

- change the log level for prod
- change the power level multiplier for test
- discuss that it's also useful for database and point to the Quarkus doc

The first two would be code examples (part of application.properties).

**Comment by agoncal** [comment]
+1

I like the idea of having a different power level for test. This way we can say "in test, the power level is 2, so we create a Hero with a power of 5 and test (with RESTAssured) that the power is now 10".

**Comment by emmanuelbernard** [comment]
As per the other issue, this does require some test adjustment if you do
that. The test suite assumes a level of 1 to pass.

**Comment by cescoffier** [comment]
I've written a bit on this.

**Comment by cescoffier** [comment]
Yes.
