### ISSUE TITLE
Reduce duplicated adoc in Azure docs

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus-workshops#302]
We should be able to use conditional includes and global configurations (like we did for different OSes with #253) to reduce the maintenance costs/risk of errors in the Azure docs, by reducing how much content is duplicated between the two sets of docs.

cc @agoncal

**Comment by agoncal** [comment]
Yes, that's definitelly something I want to do. I want the Azure workshop to become another "optional" chapter that we could include or not
