### ISSUE TITLE
Question: should we add all the necessary extensions in the bootstrap for the villain ms

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus-workshops#31]
Today it does include no explicit extension and thus the lab rat has to figure out the extension list for himself based on the techno we use (panache , postgresql etc). Should we make that problem non existent by pre populating the extensions as part of the project creation or an explicit add-extension list?

**Comment by emmanuelbernard** [comment]
Something like this  https://github.com/quarkusio/quarkus-workshops/commit/61e5e2d850a522e43476a21dfe0d5f4af21aed06 (forget the part about quarkus-workshop-super-heroes/docs/src/main/asciidoc/quarkus-native.adoc )

**Comment by agoncal** [comment]
I really like 

```
./mvnw quarkus:add-extension -Dextensions="jdbc-postgresql,hibernate-orm-panache,hibernate-validator,quarkus-resteasy-jsonb,openapi"
```

**Comment by emmanuelbernard** [comment]
Ok so we go for it. Closing this.
