### ISSUE TITLE
Bump Quarkus to the latest greatest version before Devoxx BE

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#313]

**Comment by holly-cummins** [comment]
What this tells us is that dependabot still isn't working for the Java dependencies. I wonder why?

**Comment by agoncal** [comment]
@holly-cummins oh, yes, that's true !!!

**Comment by holly-cummins** [comment]
Will be resolved by #333. (Interestingly, I had to merge #319 before dependabot opened #333.)
