### ISSUE TITLE
Offer a base version of the Villain code to download as zip

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus-workshops#32]
Villain is pretty much the same as Hero so people learn nothing (they just increase their muscle memory. Since the lab is huge, I recommend we offer as an option (likely preferred) to fetch a zip with the state of Villain the way we want it

**Comment by emmanuelbernard** [comment]
Assigning Antonio since he is into zip these days ;)

**Comment by emmanuelbernard** [comment]
An alternative that Clement proposes is to have a git clone or zip of the full repo structure but removing the hero project and whatever we want people to write. That way we skip some steps like downloading the infra zip, the villain zip.

The difficulty is that these should be in "start coding" mode, not with the full end of lab code.

**Comment by agoncal** [comment]
I like the Zip option. Basically we can start the adoc saying "either you have time and follow the guide, or you just unzip this file"

**Comment by agoncal** [comment]
See https://github.com/quarkusio/quarkus-workshops/commit/40aed2d30bc598f3eef4e69c57382faaa8367db7
