### ISSUE TITLE
Missing prereq: jq

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/quarkus-workshops#387]
Our instructions reference jq, but the jq prereq was mixed into the curl section. That meant when we moved the curl prereq to the appendix, we lost the jq prereq. We should make it its own top-level prereq and include it in the bulleted list of prereqs.

**Comment by agoncal** [comment]
Oh, just realize that we mention `jq` in the Appendix... but not how to install it though:

https://github.com/quarkusio/quarkus-workshops/blob/main/quarkus-workshop-super-heroes/docs/src/docs/asciidoc/core-appendix/appendix-installing-curl.adoc#formatting-the-curl-json-output

**Comment by holly-cummins** [comment]
Yes, it needs to get moved from the appendix to its own top-level section. What happened is that it was mixed in with curl, so when we moved curl (which we don't need) we moved jq (which we do need).

**Comment by agoncal** [comment]
It brings question though: which installation instruction should be moved to the introduction and which one to the appendix ? Or maybe we could move all the installations to the Appendix (so we can be more verbosem detail the installation, etc) and in the introduction just say "you need technology x,y,z, please check the appendix if you need to install them". If not, the introduction section would end up quite large when we select more complex versions of the workshop (eg. install Java, install Graal, install Docker, install Minikube, install Azure CLI....)

WDYT ?

**Comment by holly-cummins** [comment]
IMO, I think the rule should be "if you need it, it's in the main flow. if you don't need it except for a tiny minority on an obscure linux variant [ie, curl], it goes in the appendix." 

That's what we tried to do, but we just failed with jq. I agree that the long intro is not ideal, but I think it's also not ideal to ask people to be scrolling back and forth in the doc to make progress.

**Comment by holly-cummins** [comment]
Resolved by #417
