### ISSUE TITLE
Fix the CSS so the cards are next to each other

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#4]
The [Fight](https://github.com/quarkusio/quarkus-workshops/blob/master/quarkus-workshop-super-heroes/ui-super-heroes/src/app/fight/fight.component.html) component has two cards (one hero, one villain) that should be next to each other and in between, the two buttons ("New Fighters" and "Fight"). Instead, they are one below the other

<img width="636" alt="Capture d’écran 2019-10-02 à 15 50 40" src="https://user-images.githubusercontent.com/729277/66050004-b20c8f00-e52c-11e9-9515-1e444f353cf0.png">

**Comment by cescoffier** [comment]
![image_2019_10_03T15_19_52_111Z](https://user-images.githubusercontent.com/402301/66184249-d32fc580-e67b-11e9-85f2-242e5125fe86.png)

Done. Of course, it can still be improved a bit...
