### ISSUE TITLE
Prometheus can't acces to localhost on Linux ubuntu

### ISSUE THREAD

**Issue by rbelfils** [quarkusio/quarkus-workshops#43]
Pour pouvoir le faire communiquer avec le host, sur le service prometheus j'ai ajouté le mode réseau : Host.

ex: 
 monitoring:
        image: "prom/prometheus"
        container_name: "super-visor"
        **network_mode: host**
        ports:
          - 9090:9090
# tag::adocVolumePrometheus[]
        volumes:
          - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
# end::adocVolumePrometheus[]

**Comment by cescoffier** [comment]
Fixed.
