### ISSUE TITLE
Typo in https://quarkus.io/quarkus-workshops/super-heroes/spine.html#ui Contract Testing Section

### ISSUE THREAD

**Issue by butch500200** [quarkusio/quarkus-workshops#471]
In the Writing the first contract test section when we are creating a mock server for the findRandomHero test, it is mentioend pact will create a new server to stand up and the port conflicts and so we need a new test URL. We are instructed to add the following to the properties files for rest-fights
%test.quarkus.rest-client.hero.url=http://localhost:8083=http://localhost:8093
Checking the completed code doesn't have this line, so its clearly a copy and paste typo.

**Comment by holly-cummins** [comment]
Thanks for spotting this and taking the time to raise the issue!
