### ISSUE TITLE
Add an "call to action" icon

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-workshops#59]
Every time that the user must "do" something, an icon should be added. This visual sign should be visible enough so the user can scroll and find them pretty quickly.

**Comment by agoncal** [comment]
Looks like this issue has been fixed. Can we close it ?

**Comment by cescoffier** [comment]
Yes, it can be closed.

**Comment by agoncal** [comment]
@aureamunoz do you want to close it ?

**Comment by aureamunoz** [comment]
Yes! thanks
