### ISSUE TITLE
Section "Quarkus Augmentation" out of date (references 1.2.0)

### ISSUE THREAD

**Issue by kullmanp** [quarkusio/quarkus-workshops#61]
In the section "Quarkus Augmentation" the maven output is of version 1.2.0. I have version 1.3.2 (this is just starting the workshop without any manual changes, I think). 
The text references 
- target/transformed-classes
- target/wiring-classes
Both directories do not or no longer exist.

**Comment by cescoffier** [comment]
I rewrote this part.
