### ISSUE TITLE
typo is observability-healthcheck

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus-workshops#68]
https://quarkus.io/quarkus-workshops/super-heroes/#observability

there is this in the webpage under Directory structure

While you could **add add** health checks to all our microservices, we are focusing on the Hero microservice. So don’t forget to switch to the Hero microservice code. You can apply the same to the other microservices.

but I don't see it in the adoc pages.  Not sure if it's not fixed already, just not deployed.

**Comment by cescoffier** [comment]
@survivant The file is here: https://github.com/quarkusio/quarkus-workshops/blob/master/quarkus-workshop-super-heroes/docs/src/main/asciidoc/observability-healthcheck.adoc

Fancy a PR?

**Comment by holly-cummins** [comment]
This is now fixed, and can be closed.
