### ISSUE TITLE
docker-compose-linux.yaml file lost

### ISSUE THREAD

**Issue by rgomezcuervo** [quarkusio/quarkus-workshops#80]
In the workshop instructions: https://quarkus.io/quarkus-workshops/super-heroes/ , it's refers the docker-compose-linux.yaml file, but the repo: "Get this workshop from https://github.com/quarkusio/quarkus-workshops/tree/master/quarkus-workshop-super-heroes " , don't contains it.

Is it possible to find it again?

Thanks.

**Comment by aureamunoz** [comment]
Hi, yes, I'm on it. I'll let you know when it will be fixed

**Comment by aureamunoz** [comment]
The file has been restored, @rgomezcuervo . Let me know if you find other issues.
thank you
