### ISSUE TITLE
Fail to run event-statistics service on dev

### ISSUE THREAD

**Issue by salnikovp0** [quarkusio/quarkus-workshops#85]
Hi,

got the following error when try to run
mvn compile quarkus:dev

ailed to start application (with profile dev): java.lang.ClassCastException: io.smallrye.mutiny.context.ContextPropagationMultiInterceptor$ContextPropagationMulti cannot be cast to io.reactivex.Flowable

some issue with the extension banner on rest-fight(mvn quarkus:dev) service that the error of multiple banner.text on properties that you might check. so i remove the banner extension from the pom.xml and it works

**Comment by aureamunoz** [comment]
Hi,
The Flowable is not supported anymore, a PR is in progress to replace it: https://github.com/quarkusio/quarkus-workshops/pull/84.

Regarding the banner yes, there is a conflict when both are in the dependencies

**Comment by salnikovp0** [comment]
I did change to Multi and it works good

**Comment by cescoffier** [comment]
Fixed as #84 has been merged.
