### ISSUE TITLE
Change the landing page banner colors to be distinctive

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-workshops#9]

**Comment by cescoffier** [comment]
Hero: dodgerblue
Villain: firebrick

**Comment by agoncal** [comment]
@cescoffier it's already done (but with different colors). You want to change the colours again ?

**Comment by cescoffier** [comment]
This is the color used everywhere else for heroes and villains. I was thinking it would be nice to align on them. I can do it.

For the fight microservice, any color would be ok (except mixing dodgerblue and firebrick because that would be really ugly)
