### ISSUE TITLE
Not working tests after "CRUD Tests in HeroResourceTest" section

### ISSUE THREAD

**Issue by jgarciasm** [quarkusio/quarkus-workshops#97]
Hello, I am really new to Quarkus and I am following this awesome workshop but after adding CRUD tests of section 
[CRUD Tests in HeroResourceTest](https://quarkus.io/quarkus-workshops/super-heroes/#_crud_tests_in_heroresourcetest)
the tests was broken. 

I followed all steps and Iwhen I tried to execute the tests it throhs this error:
```
[ERROR] Tests run: 10, Failures: 0, Errors: 1, Skipped: 9, Time elapsed: 3.245 s <<< FAILURE! - in io.quarkus.workshop.superheroes.hero.HeroResourceTest
[ERROR] io.quarkus.workshop.superheroes.hero.HeroResourceTest.shouldGetInitialItems  Time elapsed: 0.005 s  <<< ERROR!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.NoSuchMethodError: 'org.testcontainers.utility.DockerImageName org.testcontainers.utility.DockerImageName.parse(java.lang.String)'

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   HeroResourceTest.shouldGetInitialItems Â» Runtime java.lang.reflect.InvocationT...
```

I search a lot in internet and I think it may be something related with **org.testcontainers** version.

**Comment by jgarciasm** [comment]
Workaround: when I add the following dependency the tests pass OK:
```
<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>testcontainers</artifactId>
    <version>1.15.2</version>
    <scope>test</scope>
</dependency>
```

Someone knows why that happens to me?

**Comment by cescoffier** [comment]
Recent Docker version changed an internal API that makes old test containers versions incompatible.

**Comment by jgarciasm** [comment]
Thank you @cescoffier!!!

**Comment by cescoffier** [comment]
Fixed with the latest rewrite.
